version: "3.4"

services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    restart: always
    ports:
      - "10087:10087"
    volumes:
      - ./v2ray-config.json:/etc/v2ray/config.json
    networks:
      - v2ray
  nginx:
      image: nginx:alpine
      container_name: nginx
      networks:
          - v2ray
      ports:
          - "80:80"
          - "443:443"
networks:
    v2ray: