version: "3.7"

services:
    v2ray:
        image: v2fly/v2fly-core
        container_name: v2ray
        restart: always
        ports:
            - "10087:10087"
        volumes:
            - ./config.json:/etc/v2ray/v2ray-config.json
        networks:
            - v2ray